"""Actualizacion de Carrera4

Revision ID: 0255c251d5a9
Revises: d877b39af4ec
Create Date: 2025-05-12 09:01:40.733575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0255c251d5a9'
down_revision: Union[str, None] = 'd877b39af4ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planes_estudio', sa.Column('id_carrera', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'planes_estudio', 'carreras', ['id_carrera'], ['id_carrera'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'planes_estudio', type_='foreignkey')
    op.drop_column('planes_estudio', 'id_carrera')
    # ### end Alembic commands ###
