"""cambio de curp a 18 caracteres

Revision ID: 0722e62425aa
Revises: 52e193375e70
Create Date: 2025-02-17 08:03:57.695858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0722e62425aa'
down_revision: Union[str, None] = '52e193375e70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alumnos', 'curp',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=18),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alumnos', 'curp',
               existing_type=sa.String(length=18),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
