"""create modulos and materias tables

Revision ID: 07ef9e5795fd
Revises: b86d5102b6b3
Create Date: 2025-06-05 10:34:14.983623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07ef9e5795fd'
down_revision: Union[str, None] = 'b86d5102b6b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    conn = op.get_bind()
    inspector = sa.inspect(conn)

    columns = [col["name"] for col in inspector.get_columns("carreras")]
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modulos',
    sa.Column('id_modulo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_modulo'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_modulos_id_modulo'), 'modulos', ['id_modulo'], unique=False)
    op.drop_constraint('carreras_id_plan_estudio_fkey', 'carreras', type_='foreignkey', if_exists=True)
    if "id_plan_estudio" in columns:
        op.drop_column("carreras", "id_plan_estudio")    
    op.alter_column('materias', 'nombre',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('materias', 'creditos',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('materias', 'tipo',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('materias', 'id_modulo',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_materias_id_materia'), 'materias', ['id_materia'], unique=False)
    op.create_foreign_key(None, 'materias', 'modulos', ['id_modulo'], ['id_modulo'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'materias', type_='foreignkey')
    op.drop_index(op.f('ix_materias_id_materia'), table_name='materias')
    op.alter_column('materias', 'id_modulo',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('materias', 'tipo',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('materias', 'creditos',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('materias', 'nombre',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.add_column('carreras', sa.Column('id_plan_estudio', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('carreras_id_plan_estudio_fkey', 'carreras', 'planes_estudio', ['id_plan_estudio'], ['id_plan_estudio'])
    op.drop_index(op.f('ix_modulos_id_modulo'), table_name='modulos')
    op.drop_table('modulos')
    # ### end Alembic commands ###
