"""create planestudio-materias

Revision ID: 086c8acdac11
Revises: f79cb6e3dff2
Create Date: 2025-06-05 15:41:41.328183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '086c8acdac11'
down_revision: Union[str, None] = 'f79cb6e3dff2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
