"""create plan_estudio_materia table

Revision ID: 0c565f1ca2d3
Revises: 086c8acdac11
Create Date: 2025-06-05 22:59:30.289879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c565f1ca2d3'
down_revision: Union[str, None] = '086c8acdac11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_estudio_materia',
    sa.Column('id_plan_estudio', sa.Integer(), nullable=False),
    sa.Column('id_materia', sa.Integer(), nullable=False),
    sa.Column('semestre', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_materia'], ['materias.id_materia'], ),
    sa.ForeignKeyConstraint(['id_plan_estudio'], ['planes_estudio.id_plan_estudio'], ),
    sa.PrimaryKeyConstraint('id_plan_estudio', 'id_materia')
    )
    op.drop_index('ix_plan_estudio_materias_id', table_name='plan_estudio_materias')
    op.drop_table('plan_estudio_materias')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_estudio_materias',
    sa.Column('id_materia', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('semestre', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_plan_estudio', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_materia'], ['materias.id_materia'], name='plan_estudio_materias_id_materia_fkey'),
    sa.ForeignKeyConstraint(['id_plan_estudio'], ['planes_estudio.id_plan_estudio'], name='plan_estudio_materias_id_plan_estudio_fkey')
    )
    op.create_index('ix_plan_estudio_materias_id', 'plan_estudio_materias', ['id'], unique=False)
    op.drop_table('plan_estudio_materia')
    # ### end Alembic commands ###
