"""Fix relaciones

Revision ID: 3114b5f2aadf
Revises: 5ef55c60542a
Create Date: 2025-02-24 08:17:22.751899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3114b5f2aadf'
down_revision: Union[str, None] = '5ef55c60542a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carreras', sa.Column('id_plan_estudio', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'carreras', 'planes_estudio', ['id_plan_estudio'], ['id_plan_estudio'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'carreras', type_='foreignkey')
    op.drop_column('carreras', 'id_plan_estudio')
    # ### end Alembic commands ###
