"""relaciones v2

Revision ID: 3a1c5641f8d4
Revises: 3114b5f2aadf
Create Date: 2025-02-25 22:52:25.629963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a1c5641f8d4'
down_revision: Union[str, None] = '3114b5f2aadf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alumnos', 'generacion',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_column('grupo_alumnos', 'id_grupo_alumno')
    op.drop_column('grupo_alumnos', 'tipo_inscripcion')
    op.drop_constraint('plan_estudio_materias_id_carrera_fkey', 'plan_estudio_materias', type_='foreignkey')
    op.drop_column('plan_estudio_materias', 'id_plan_estudio_materia')
    op.drop_column('plan_estudio_materias', 'id_carrera')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan_estudio_materias', sa.Column('id_carrera', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('plan_estudio_materias', sa.Column('id_plan_estudio_materia', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_foreign_key('plan_estudio_materias_id_carrera_fkey', 'plan_estudio_materias', 'carreras', ['id_carrera'], ['id_carrera'])
    op.add_column('grupo_alumnos', sa.Column('tipo_inscripcion', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('grupo_alumnos', sa.Column('id_grupo_alumno', sa.INTEGER(), autoincrement=True, nullable=False))
    op.alter_column('alumnos', 'generacion',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    # ### end Alembic commands ###
