"""Relacion Grupo Periodo

Revision ID: 48dab78d96e7
Revises: 0255c251d5a9
Create Date: 2025-05-22 09:47:09.148713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48dab78d96e7'
down_revision: Union[str, None] = '0255c251d5a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('carreras_id_plan_estudio_fkey', 'carreras', type_='foreignkey')
    op.drop_column('carreras', 'id_plan_estudio')
    op.add_column('periodos', sa.Column('periodo', sa.String(length=255), nullable=False))
    op.add_column('periodos', sa.Column('fecha_inicio', sa.String(length=50), nullable=False))
    op.add_column('periodos', sa.Column('fecha_fin', sa.String(length=50), nullable=False))
    op.drop_column('periodos', 'nombre')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('periodos', sa.Column('nombre', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('periodos', 'fecha_fin')
    op.drop_column('periodos', 'fecha_inicio')
    op.drop_column('periodos', 'periodo')
    op.add_column('carreras', sa.Column('id_plan_estudio', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('carreras_id_plan_estudio_fkey', 'carreras', 'planes_estudio', ['id_plan_estudio'], ['id_plan_estudio'])
    # ### end Alembic commands ###
