"""initial migration 2

Revision ID: 52e193375e70
Revises: 421c6d9823e1
Create Date: 2025-02-16 13:34:54.626961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52e193375e70'
down_revision: Union[str, None] = '421c6d9823e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carreras',
    sa.Column('id_carrera', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_carrera')
    )
    op.create_table('materias',
    sa.Column('id_materia', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('creditos', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=255), nullable=False),
    sa.Column('id_modulo', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_materia')
    )
    op.create_table('periodos',
    sa.Column('id_periodo', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_periodo')
    )
    op.create_table('planes_estudio',
    sa.Column('id_plan_estudio', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_plan_estudio')
    )
    op.create_table('alumnos',
    sa.Column('id_alumno', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('ape_paterno', sa.String(length=255), nullable=False),
    sa.Column('ape_materno', sa.String(length=255), nullable=False),
    sa.Column('num_control', sa.Integer(), nullable=False),
    sa.Column('curp', sa.String(length=255), nullable=False),
    sa.Column('id_carrera', sa.Integer(), nullable=False),
    sa.Column('turno', sa.String(length=255), nullable=False),
    sa.Column('local', sa.Boolean(), nullable=False),
    sa.Column('generacion', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['id_carrera'], ['carreras.id_carrera'], ),
    sa.PrimaryKeyConstraint('id_alumno')
    )
    op.create_table('grupos',
    sa.Column('id_grupo', sa.Integer(), nullable=False),
    sa.Column('id_periodo', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=255), nullable=False),
    sa.Column('turno', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['id_periodo'], ['periodos.id_periodo'], ),
    sa.PrimaryKeyConstraint('id_grupo')
    )
    op.create_table('plan_estudio_materias',
    sa.Column('id_plan_estudio_materia', sa.Integer(), nullable=False),
    sa.Column('id_materia', sa.Integer(), nullable=False),
    sa.Column('semestre', sa.Integer(), nullable=False),
    sa.Column('id_carrera', sa.Integer(), nullable=False),
    sa.Column('id_plan_estudio', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_carrera'], ['carreras.id_carrera'], ),
    sa.ForeignKeyConstraint(['id_materia'], ['materias.id_materia'], ),
    sa.ForeignKeyConstraint(['id_plan_estudio'], ['planes_estudio.id_plan_estudio'], ),
    sa.PrimaryKeyConstraint('id_plan_estudio_materia')
    )
    op.create_table('grupo_alumnos',
    sa.Column('id_grupo_alumno', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_grupo', sa.Integer(), nullable=False),
    sa.Column('id_alumno', sa.Integer(), nullable=False),
    sa.Column('tipo_inscripcion', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_alumno'], ['alumnos.id_alumno'], ),
    sa.ForeignKeyConstraint(['id_grupo'], ['grupos.id_grupo'], ),
    sa.PrimaryKeyConstraint('id_grupo_alumno')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grupo_alumnos')
    op.drop_table('plan_estudio_materias')
    op.drop_table('grupos')
    op.drop_table('alumnos')
    op.drop_table('planes_estudio')
    op.drop_table('periodos')
    op.drop_table('materias')
    op.drop_table('carreras')
    # ### end Alembic commands ###
