"""create planestudio-materias

Revision ID: 69ba7aa3fff1
Revises: 754b88cdbc66
Create Date: 2025-06-05 14:54:26.063922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69ba7aa3fff1'
down_revision: Union[str, None] = '754b88cdbc66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
