"""create planestudio-materias

Revision ID: 754b88cdbc66
Revises: 07ef9e5795fd
Create Date: 2025-06-05 14:50:38.415419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '754b88cdbc66'
down_revision: Union[str, None] = '07ef9e5795fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan_estudio_materias', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('plan_estudio_materias', 'id_plan_estudio',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('plan_estudio_materias', 'id_materia',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('plan_estudio_materias', 'semestre',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_plan_estudio_materias_id'), 'plan_estudio_materias', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plan_estudio_materias_id'), table_name='plan_estudio_materias')
    op.alter_column('plan_estudio_materias', 'semestre',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('plan_estudio_materias', 'id_materia',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('plan_estudio_materias', 'id_plan_estudio',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('plan_estudio_materias', 'id')
    # ### end Alembic commands ###
