"""init migraciones

Revision ID: 91e54694cc48
Revises: 
Create Date: 2025-02-13 23:09:04.846239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91e54694cc48'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carreras',
    sa.Column('id_carrera', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_carrera')
    )
    op.create_index(op.f('ix_carreras_id_carrera'), 'carreras', ['id_carrera'], unique=False)
    op.create_table('alumnos',
    sa.Column('id_alumno', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('ape_paterno', sa.String(length=255), nullable=False),
    sa.Column('ape_materno', sa.String(length=255), nullable=False),
    sa.Column('num_control', sa.Integer(), nullable=False),
    sa.Column('curp', sa.String(length=255), nullable=False),
    sa.Column('id_carrera', sa.Integer(), nullable=True),
    sa.Column('turno', sa.String(length=255), nullable=False),
    sa.Column('local', sa.Boolean(), nullable=False),
    sa.Column('generacion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_carrera'], ['carreras.id_carrera'], ),
    sa.PrimaryKeyConstraint('id_alumno')
    )
    op.create_index(op.f('ix_alumnos_id_alumno'), 'alumnos', ['id_alumno'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alumnos_id_alumno'), table_name='alumnos')
    op.drop_table('alumnos')
    op.drop_index(op.f('ix_carreras_id_carrera'), table_name='carreras')
    op.drop_table('carreras')
    # ### end Alembic commands ###
