"""relacion alumno 2

Revision ID: a209d4f2ad34
Revises: 95eed4771d06
Create Date: 2025-06-06 09:31:04.264370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a209d4f2ad34'
down_revision: Union[str, None] = '95eed4771d06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('alumnos_id_carrera_fkey'), 'alumnos', type_='foreignkey')
    op.drop_column('alumnos', 'id_carrera')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alumnos', sa.Column('id_carrera', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('alumnos_id_carrera_fkey'), 'alumnos', 'carreras', ['id_carrera'], ['id_carrera'])
    # ### end Alembic commands ###
