"""cambiar relacion alumno a plan_estudio

Revision ID: a21d4fe6970e
Revises: 0255c251d5a9
Create Date: 2025-06-04 10:52:12.013935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a21d4fe6970e'
down_revision: Union[str, None] = '0255c251d5a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Paso 1: Agregar columna como nullable primero
    op.add_column('alumnos', sa.Column('id_plan_estudio', sa.Integer(), nullable=True))

    # Paso 2: Ejecutar SQL para llenar id_plan_estudio basado en carrera
    op.execute('''
        UPDATE alumnos
        SET id_plan_estudio = (
            SELECT id_plan_estudio
            FROM planes_estudio
            WHERE planes_estudio.id_carrera = alumnos.id_carrera
            ORDER BY planes_estudio.id_plan_estudio DESC
            LIMIT 1
        )
    ''')

    # Paso 3: Hacer NOT NULL la columna ahora que tiene valores
    op.alter_column('alumnos', 'id_plan_estudio', nullable=False)

    # Paso 4: Agregar foreign key si no lo hace Alembic automáticamente
    op.create_foreign_key(
        'fk_alumnos_plan_estudio',
        'alumnos', 'planes_estudio',
        ['id_plan_estudio'], ['id_plan_estudio']
    )
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('alumnos', sa.Column('id_plan_estudio', sa.Integer(), nullable=False))
    # op.drop_constraint('alumnos_id_carrera_fkey', 'alumnos', type_='foreignkey')
    # op.create_foreign_key(None, 'alumnos', 'planes_estudio', ['id_plan_estudio'], ['id_plan_estudio'])
    # op.drop_column('alumnos', 'id_carrera')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alumnos', sa.Column('id_carrera', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'alumnos', type_='foreignkey')
    op.create_foreign_key('alumnos_id_carrera_fkey', 'alumnos', 'carreras', ['id_carrera'], ['id_carrera'])
    op.drop_column('alumnos', 'id_plan_estudio')
    # ### end Alembic commands ###
