"""update alumnos

Revision ID: a4eb03c47c31
Revises: 47ad22cc1c65
Create Date: 2025-02-18 22:27:54.346891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4eb03c47c31'
down_revision: Union[str, None] = '47ad22cc1c65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alumnos', 'local')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alumnos', sa.Column('local', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
