"""create planestudio-materias

Revision ID: f79cb6e3dff2
Revises: 69ba7aa3fff1
Create Date: 2025-06-05 15:36:22.103554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f79cb6e3dff2'
down_revision: Union[str, None] = '69ba7aa3fff1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
